// loan-quoter-react/src/components/Button.tsx
function Button(props: any) {
    return (
        <button
          type="button"
          className="h-10 w-10 flex items-center justify-center font-bold text-white
          text-2xl bg-lime-500 rounded-full hover:outline-none hover:ring-2
          hover:ring-offset-2 hover:ring-lime-500"
          onClick={props.fn}
        >{props.operador}</button>
    )
}

export default Button;

// loan-quoter-vue/src/components/Button.vue
<script setup lang="ts">
    const props = defineProps({
        operador: String
    });
</script>

<template>
    <button
        type="button"
        class="h-10 w-10 flex items-center justify-center font-bold
        bg-lime-500 rounded-full hover:outline-none hover:ring-2
        hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
        @click="$emit('fn')"
    >{{operador}}</button>
</template>
